export const bikes = [{
    id: 'ALine',
    startPrijs:  [1100],
    versnelling: [3],
    versnellingPrijs: [0],
    stuur: ['m'],
    stuurPrijs:[0],
    rack:['geen'],
    rackPrijs:[0],
    zadel: ['standaard'],
    zadelPrijs: [0],
    zadelHoogte: ['standaard'],
    zadelHoogtePrijs: [0],
    verlichting: ['reflector'],
    verlichtingPrijs: [0],
    kleur: ['papyrus white'], 
    kleurPrijs: [0],
},{
    id: 'CLine',
    startPrijs: [1599],
    versnelling: ['2', '6'],
    versnellingPrijs: [0, 150],
    stuur: ['s','m','h'],
    stuurPrijs:[0,0,0],
    rack:['spatborden', 'bagagedrager'],
    rackPrijs:[0,100],
    zadel: ['standaard', 'standaard wide', 'B17', 'C17'],
    zadelPrijs:[0,0,116,76],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,71],
    verlichting: ['reflector','battery','dynamo'],
    verlichtingPrijs: [0,100,180],
    kleur: ['Black Matt','Bumblebee Yellow', 'Dune Sand', 'Gloss Black Laquer', 'Ocean Blue', 'Racing Green'], 
    kleurPrijs: [0,0,0,265,0,0],
},{
    id: 'CLineElectric',
    startPrijs: [3450],
    versnelling: ['4', '12'],
    versnellingPrijs: [0, 300],
    stuur: ['m','h'],
    stuurPrijs:[0,0],
    rack:['spatborden', 'bagagedrager'],
    rackPrijs:[0,63.82],
    zadel: ['standaard', 'standaard wide'],
    zadelPrijs:[0,0],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,42.54],
    verlichting: ['geintergreed'],
    verlichtingPrijs: [0],
    kleur: ['Black','Bumblebee Yellow', 'Dune Sand', 'Gloss Black Laquer', 'Ocean Blue', 'Racing Green'], 
    kleurPrijs: [0,0,0,265,0,0],
},{
    id: 'TLine',
    startPrijs: [4950],
    versnelling: ['1','4', '12'],
    versnellingPrijs: [0,299, 574],
    stuur: ['m'],
    stuurPrijs:[0],
    rack:['spatborden'],
    rackPrijs:[0],
    zadel: ['standaard super light'],
    zadelPrijs:[0],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,71],
    verlichting: ['reflector','battery'],
    verlichtingPrijs: [0,100],
    kleur: ['blasted Ti'], 
    kleurPrijs: [0],
},{
    id: 'PLine',
    startPrijs: [2849],
    versnelling: ['4','12'],
    versnellingPrijs: [0,250],
    stuur: ['s','m','h'],
    stuurPrijs:[0,0,0],
    rack:['spatborden','bagagedrager'],
    rackPrijs:[0,110],
    zadel: ['standaard super light'],
    zadelPrijs:[0],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,71],
    verlichting: ['reflector','battery'],
    verlichtingPrijs: [0,100],
    kleur: ['Midnight Black Metalic','Bolt Blue Lacquer','Bronze Sky','Lunar Ice'], 
    kleurPrijs: [0,120,0,0],
},{
    id: 'PLineElectric',
    startPrijs: [4199],
    versnelling: ['4', '12'],
    versnellingPrijs: [0,200],
    stuur: ['m','h'],
    stuurPrijs:[0,0],
    rack:['spatborden','bagagedrager'],
    rackPrijs:[0,120],
    zadel: ['standaard super light'],
    zadelPrijs:[0],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,71],
    verlichting: ['intergrated'],
    verlichtingPrijs: [0],
    kleur: ['Midnight Black Metalic','Bolt Blue Lacquer','Bronze Sky','Lunar Ice'], 
    kleurPrijs: [0,120,0,0],
},{
    id: 'GLine',
    startPrijs: [2969],
    versnelling: ['8'],
    versnellingPrijs: [0],
    stuur: ['s'],
    stuurPrijs:[0],
    rack:['spatborden','bagagedrager'],
    rackPrijs:[0,120],
    zadel: ['standaard'],
    zadelPrijs:[0],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,0],
    verlichting: ['reflector','battery lezyne'],
    verlichtingPrijs: [0,110],
    kleur: ['Adventure Orange','Forest Green','Traildust White'], 
    kleurPrijs: [0,0,0],
},{
    id: 'GLineElectric',
    startPrijs: [3999],
    versnelling: ['8'],
    versnellingPrijs: [0],
    stuur: ['s'],
    stuurPrijs:[0],
    rack:['bagagedrager'],
    rackPrijs:[0],
    zadel: ['standaard'],
    zadelPrijs:[0],
    zadelHoogte: ['standaard','extended','telescopic'],
    zadelHoogtePrijs: [0,0,0],
    verlichting: ['intergrated'],
    verlichtingPrijs: [0],
    kleur: ['Adventure Orange','Forest Green','Traildust White'], 
    kleurPrijs: [0,0,0],
},
]